#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'sinatra'
require 'prawn'
require 'prawn/measurement_extensions'

def generateMovementTray(rows, cols, filename, public_filename, base)

    pdf = Prawn::Document.new

    pdf.text "PDF Movement Tray"
    pdf.stroke_horizontal_rule
    pdf.move_down 10
    pdf.text "#{base[0]}x#{base[1]}mm bases, #{rows} ranks, #{cols} models per rank"
    pdf.text "Generated by pdfMovementTray.com"
    pdf.text "Permanent download link: https://pdfMovementTray.com#{public_filename}"

    pdf.move_down 30
    pdf.text "Cut along the lines below:"

    y = base[1].mm
    x = 0
    
    rows.times do
        cols.times do |i|
            
            pdf.stroke do
                pdf.rectangle [x,y], base[0].mm, base[1].mm
            end

            x += base[0].mm + 1.mm
        end
        x = 0
        y += base[1].mm + 1.mm
    end

    pdf.render_file filename
end

get '/' do
  erb :form
end

post '/' do

  case params['base'] 
    when "standard"
        base = [20, 20]
    when "large" 
        base = [25, 25]
    when "monster"
        base = [40, 40]
    when "cavalry"
        base = [25, 50]
  end

  rows = params['rows'].to_i
  cols = params['cols'].to_i

  @filename = '/'+params['base']+'-'+params['rows']+'x'+params['cols']+'.pdf'
  file = 'public/'+params['base']+'-'+params['rows']+'x'+params['cols']+'.pdf'

  generateMovementTray(rows, cols, file, @filename, base) unless File.exists?(file)

  erb :gen
end


not_found do
 #status 404
 erb :not_found
end
